eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
    register-with-eureka: false # not show in eureka page
  server:
    enable-self-preservation: false # default services exist
spring:
  application:
    name: eureka
#server:
#  port: 8761