eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
  # define the name
  instance:
    hostname: clientName
spring:
  application:
    name: client